/* =====================================================================
   TRIBUTE — CHAPTER DESIGN ENTRIES (game skeleton)
   Source: the user's per-chapter design doc (Prologue -> Chapter 15 so far).
   Fields: title, sum (story summary), loc (main location text), chars (playable),
           events (key events), unlocks (gameplay unlocks), rewards.
   The mechanical parts live elsewhere:
     locations / spots / routes ..... world.js (unlock: {ch:n} = chapter n completed)
     chapter gating by place ........ CH_LOC in world.js
     recruits ....................... JOIN_CH in core.js
     skill-tree unlocks ............. TREE_CH in skilltree.js
   Chapters 16+ are still to be written.
   ===================================================================== */
const CHAPTER_DESIGN = {
 0:{ title:'The Fate of Tribute', loc:'🏯 Imperial Capital — Imperial Palace, Training Grounds, Imperial Garden',
  chars:['jade'],
  sum:'Tribute remains trapped under the shadow of Xima\'s ancient curse. King Greyson searches for someone able to protect the island\'s future. Jade Gold, a young Imperial Guard with mysterious abilities, is summoned to the Palace. Talented with the sword, she struggles to understand the strange visions and powers hidden within her.',
  events:['Jade receives her mission from King Greyson','Introduction to Tribute\'s history and Xima\'s curse','Jade begins investigating the island\'s mysteries','First hints of her unusual powers appear'],
  unlocks:['Character system','Training Grounds','Journal','Codex','Royal communication: pigeon post (upgrades to the Imperial Bracelet)'],
  rewards:['Imperial Guard status','Basic sword skills','Tribute World Map unlocked']},
 1:{ title:'The Recruitment Scroll', loc:'🏯 Imperial Capital — Recruitment Hall, Training Grounds, City Streets',
  chars:['jade','chad','sky'],
  sum:'A mysterious recruitment request brings two outsiders into Jade\'s path. Roc Chadwick, a skilled mercenary, answers it and arrives in Tribute with Sky Yale. Jade meets Chad for the first time and senses something unusual about him.',
  events:['Chad accepts the mercenary request','Jade evaluates Chad\'s abilities','First interaction between Jade and Chad','Sky joins their journey'],
  unlocks:['Party system (Jade + Chad + Sky; Sky starts as a support NPC)','Mercenary quest system (Recruitment Hall board)'],
  rewards:['Chad recruited','New combat style unlocked','Mercenary quest system']},
 2:{ title:'The Mercenary Trial', loc:'⚔️ Imperial Guard Training Grounds',
  chars:['jade','chad'],
  sum:'Before accepting Chad as a true companion, Jade tests him. Jade fights with discipline and Imperial training; Chad fights through instinct and experience. They clash constantly, but Jade recognises he is far more capable than an ordinary mercenary.',
  events:['Jade challenges Chad','Training battle begins','Chad demonstrates his martial ability','Mutual respect begins forming'],
  unlocks:['Combat tutorial: basic attacks, skills, defence, party switching'],
  rewards:['Chad skill tree unlocked','Training Grounds expanded']},
 3:{ title:'Three Blows', loc:'🏯 Imperial Capital · ⚔️ Training Grounds',
  chars:['jade','chad','sky'],
  sum:'Jade and Chad keep testing each other. Jade notices Chad\'s strength and style are unlike anything she has seen. Their relationship begins as rivalry, but a strange familiarity develops. Sky begins to show his admiration for Jade.',
  events:['Jade and Chad\'s rivalry develops','Sky\'s feelings toward Jade begin appearing','Party dynamics are established','First hints of hidden identities emerge'],
  unlocks:['Bond system (Jade × Chad: Rivalry · Jade × Sky: Friendship)'],
  rewards:['Sky support abilities unlocked (Sky skill tree)','Party interaction system']},
 4:{ title:'The Journey Begins', loc:'🌲 Tribute Wilderness — roads outside the capital, forest paths, travel camps',
  chars:['jade','chad','sky'],
  sum:'The group receives its first major mission beyond the capital and begins travelling across Tribute. Closer to the island\'s hidden dangers, Jade\'s visions are increasingly disturbed by something. The journey becomes a search for the truth behind the curse.',
  events:['Party leaves the Imperial Capital','First exploration outside the city','Encounter with dangerous creatures','Jade\'s clairvoyance becomes unstable'],
  unlocks:['Field exploration','World map travel (horse carriage)','Random encounters','Gathering','Camping'],
  rewards:['Exploration unlocked','New skills available']},
 5:{ title:'Into Faepool', loc:'🌲 Faepool Territory — Faepool Harbour, forest routes, first village',
  chars:['jade','chad','sky'],
  sum:'The group reaches the border region of Faepool, a land of forests and traditional villages. It looks peaceful, but Jade senses something wrong; her clairvoyance becomes harder to use, suggesting another force is interfering. The investigation into Xima\'s influence begins.',
  events:['Arrival at Faepool','Investigation begins','Strange magical interference discovered','Party prepares to search deeper into the region'],
  unlocks:['New region map: Faepool','Village quests','NPC reputation (renown)','Side quests','Regional exploration'],
  rewards:['Faepool unlocked','New quest chain begins','Xima investigation continues']},
 6:{ title:'The First Village', loc:'🏘 Vigil Village — village centre, inn, market, riverside, surrounding forest',
  chars:['jade','chad','sky'],
  sum:'The group arrives at the first village. It seems peaceful, but Jade\'s clairvoyance is unreliable: an unknown force is blocking her sight. Xima\'s influence may have reached further than expected.',
  events:['Party settles in Vigil Village','Jade investigates the magical interference','Villagers share rumours of unusual events','The party searches for clues about Xima\'s followers'],
  unlocks:['Village exploration','NPC conversations','Side quests','Local reputation','Investigation quests'],
  rewards:['Faepool village access','New investigation quests','Regional quest board unlocked']},
 7:{ title:'The Festival of Vigil', loc:'🏮 Vigil Village Festival',
  chars:['jade','chad','sky'],
  sum:'While investigating, the party stays for the village\'s traditional festival. Wandering the festival, Jade begins to question her own feelings and the complicated relationships forming around her.',
  events:['Festival begins','Jade learns about Vigil traditions','Sky\'s feelings toward Jade become clearer','Chad\'s behaviour creates tension'],
  unlocks:['Bond events','Character conversations','Relationship points'],
  rewards:['Bond EXP','Village reputation']},
 8:{ title:'The Hidden Message', loc:'🏘 Vigil Village · 🌲 Faepool Forest',
  chars:['jade','chad','sky'],
  sum:'Jade receives an unexpected message connected to the wider mission. It forces the party to reconsider their assumptions. Jade begins to suspect the curse, her visions and the people around her may all be connected.',
  events:['New information received','Investigation deepens','Party follows new clues','Jade questions her own destiny'],
  unlocks:['Main quest branch','Quest choices','Story decisions'],
  rewards:['New story route unlocked','Codex entries added']},
 9:{ title:'The Dark Influence', loc:'🌲 Faepool Forest',
  chars:['jade','chad','sky'],
  sum:'The party finds evidence that Xima\'s influence is affecting the region. Faepool\'s peaceful appearance hides deeper problems, and corrupted enemies appear. Jade must rely on both her combat skills and her unstable powers.',
  events:['First major encounters with corrupted enemies','Investigation into Xima\'s followers','Jade\'s powers become harder to control'],
  unlocks:['Field combat expansion','Enemy encounters','Skill upgrades','Equipment upgrades'],
  rewards:['Combat EXP','New skills','Enemy codex (bestiary) entries']},
 10:{ title:'The Swamp of Frog Mahan', loc:'🐸 Frog Mahan Swamp — poison marsh, hidden paths, corrupted forest',
  chars:['jade','chad','sky'],
  sum:'Following clues, the party travels toward the territory of Frog Mahan, one of Xima\'s weaker servants. The swamp tests their teamwork. Jade learns that defeating Xima\'s followers may reveal more about the curse.',
  events:['Party enters the swamp','Battles corrupted creatures','Discovers Frog Mahan\'s influence','Prepares for a major confrontation'],
  unlocks:['Boss battle system','Status effects','Environmental hazards','Boss patterns'],
  rewards:['Boss reward','Rare materials','New abilities']},
 11:{ title:'The Truth Beneath Faepool', loc:'🌲 Faepool Territory — ancient forest path, forgotten ruins, hidden caves',
  chars:['jade','chad','sky'],
  sum:'The party uncovers deeper secrets: the disturbances are part of a larger connection to Xima\'s curse. With her clairvoyance still unstable, Jade relies more on her companions and learns that not every truth can be found through visions.',
  events:['Party investigates ancient locations','Jade discovers traces of old magic','Chad and Sky assist Jade in different ways','More about Xima\'s influence is revealed'],
  unlocks:['Ancient ruin exploration','Puzzle areas','Hidden treasures','Lore discoveries'],
  rewards:['Ancient records added to Codex','New equipment','Party EXP']},
 12:{ title:'The Witch\'s Shadow', loc:'🌫 Ancient Ruins',
  chars:['jade','chad','sky'],
  sum:'The party finds evidence of the ancient witch whose curse has shaped Tribute\'s history. Jade\'s visions grow stronger but unclear: warnings, memories, or a connection to something deeper in herself.',
  events:['Jade encounters traces of ancient magic','Xima\'s presence becomes more apparent','The curse may have multiple layers','Jade questions her connection to the past'],
  unlocks:['Vision events','Story visions','Hidden lore scenes','Prophecy fragments'],
  rewards:['Codex entries: Xima, Ancient Magic, Tribute History']},
 13:{ title:'The Border of Faepool', loc:'⚓ Faepool Border — harbour, trading posts, border settlements',
  chars:['jade','chad','sky'],
  sum:'The party reaches the edge of Faepool and prepares for the next stage. Chad is no longer simply a mercenary and Sky\'s loyalty has become important, but unresolved feelings and hidden secrets create tension in the group.',
  events:['Party prepares for the next journey','New information reaches Jade','Relationships develop','New threats are hinted'],
  unlocks:['Travel system expansion: boat travel','Regional map movement','Merchant system'],
  rewards:['New travel routes','Equipment upgrades']},
 14:{ title:'The Dark Inn Incident', loc:'🏚 Dark Inn',
  chars:['jade','chad','sky'],
  sum:'The party meets a mysterious inn tied to a dangerous incident. Jade wakes in a confusing situation involving Chad and unknown forces, leaving her unsure who to trust.',
  events:['Strange events occur at the inn','Jade investigates what happened','Chad\'s actions create uncertainty','Hidden motives begin surfacing'],
  unlocks:['Investigation events','Dialogue choices','Relationship changes','Hidden information'],
  rewards:['Character bond changes','New story clues']},
 15:{ title:'Journey Across the Sea', loc:'🌊 Sea Route — boat, ocean routes, coastal areas',
  chars:['jade','chad','sky'],
  sum:'Leaving the inn, the party travels by sea. Jade reflects on her strange powers, the ancient witch\'s messages and her feelings toward her companions. The journey forces the group to rely on each other.',
  events:['Party travels by boat','Jade continues searching for answers','Character relationships develop','New destination approaches'],
  unlocks:['Sea travel','Exploration routes','Random encounters','Travel events'],
  rewards:['New region unlocked','Story progression']},
};
