/* =====================================================================
   TRIBUTE — CHAPTER DESIGN ENTRIES (game skeleton)
   Source: the user's per-chapter design doc (Prologue -> Chapter 15 so far).
   Fields: title, sum (story summary), loc (main location text), chars (playable),
           events (key events), unlocks (gameplay unlocks), rewards.
   The mechanical parts live elsewhere:
     locations / spots / routes ..... world.js (unlock: {ch:n} = chapter n completed)
     chapter gating by place ........ CH_LOC in world.js
     recruits ....................... JOIN_CH in core.js
     skill-tree unlocks ............. TREE_CH in skilltree.js
   Chapters 31+ are still to be written.
   ===================================================================== */
const CHAPTER_DESIGN = {
 0:{ title:'The Fate of Tribute', loc:'🏯 Imperial Capital — Imperial Palace, Training Grounds, Imperial Garden',
  chars:['jade'],
  sum:'Tribute remains trapped under the shadow of Xima\'s ancient curse. King Greyson searches for someone able to protect the island\'s future. Jade Gold, a young Imperial Guard with mysterious abilities, is summoned to the Palace. Talented with the sword, she struggles to understand the strange visions and powers hidden within her.',
  events:['Jade receives her mission from King Greyson','Introduction to Tribute\'s history and Xima\'s curse','Jade begins investigating the island\'s mysteries','First hints of her unusual powers appear'],
  unlocks:['Character system','Training Grounds','Journal','Codex','Royal communication: pigeon post (upgrades to the Imperial Bracelet)'],
  rewards:['Imperial Guard status','Basic sword skills','Tribute World Map unlocked']},
 1:{ title:'The Recruitment Scroll', loc:'🏯 Imperial Capital — Recruitment Hall, Training Grounds, City Streets',
  chars:['jade'],
  sum:'A mysterious recruitment request brings two outsiders into Jade\'s path. Roc Chadwick, a skilled mercenary, answers it and arrives in Tribute with Sky Yale. Jade meets Chad for the first time and senses something unusual about him.',
  events:['Chad accepts the mercenary request','Jade evaluates Chad\'s abilities','First interaction between Jade and Chad','Sky joins their journey'],
  unlocks:['Mercenary quest system (Recruitment Hall board)'],
  rewards:['Chad and Sky introduced (they join the party in Chapter 3)','New combat style seen','Mercenary quest system']},
 2:{ title:'The Mercenary Trial', loc:'⚔️ Imperial Guard Training Grounds',
  chars:['jade'],
  sum:'Before accepting Chad as a true companion, Jade tests him. Jade fights with discipline and Imperial training; Chad fights through instinct and experience. They clash constantly, but Jade recognises he is far more capable than an ordinary mercenary.',
  events:['Jade challenges Chad','Training battle begins','Chad demonstrates his martial ability','Mutual respect begins forming'],
  unlocks:['Combat tutorial (sparring battle: Jade vs Chad): basic attacks, skills, defence'],
  rewards:['Chad skill tree unlocked','Training Grounds expanded']},
 3:{ title:'Three Blows', loc:'🏯 Imperial Capital · ⚔️ Training Grounds',
  chars:['jade','chad','sky'],
  sum:'Jade and Chad keep testing each other. Jade notices Chad\'s strength and style are unlike anything she has seen. Their relationship begins as rivalry, but a strange familiarity develops. Sky begins to show his admiration for Jade.',
  events:['Jade and Chad\'s rivalry develops','Sky\'s feelings toward Jade begin appearing','Party dynamics are established','First hints of hidden identities emerge'],
  unlocks:['Party system: Chad and Sky join (party switching)','Bond system (Jade × Chad: Rivalry · Jade × Sky: Friendship)'],
  rewards:['Chad and Sky recruited','Sky support abilities unlocked (Sky skill tree)','Party interaction system']},
 4:{ title:'The Journey Begins', loc:'🌲 Tribute Wilderness — roads outside the capital, forest paths, travel camps',
  chars:['jade','chad','sky'],
  sum:'The group receives its first major mission beyond the capital and begins travelling across Tribute. Closer to the island\'s hidden dangers, Jade\'s visions are increasingly disturbed by something. The journey becomes a search for the truth behind the curse.',
  events:['Party leaves the Imperial Capital','First exploration outside the city','Encounter with dangerous creatures','Jade\'s clairvoyance becomes unstable'],
  unlocks:['Field exploration','World map travel (horse carriage)','Random encounters','Gathering','Camping'],
  rewards:['Exploration unlocked','New skills available']},
 5:{ title:'Into Faepool', loc:'🌲 Faepool Territory — Faepool Harbour, forest routes, first village',
  chars:['jade','chad','sky'],
  sum:'The group reaches the border region of Faepool, a land of forests and traditional villages. It looks peaceful, but Jade senses something wrong; her clairvoyance becomes harder to use, suggesting another force is interfering. The investigation into Xima\'s influence begins.',
  events:['Arrival at Faepool','Investigation begins','Strange magical interference discovered','Party prepares to search deeper into the region'],
  unlocks:['New region map: Faepool','Village quests','NPC reputation (renown)','Side quests','Regional exploration'],
  rewards:['Faepool unlocked','New quest chain begins','Xima investigation continues']},
 6:{ title:'The First Village', loc:'🏘 Vigil Village — village centre, inn, market, riverside, surrounding forest',
  chars:['jade','chad','sky'],
  sum:'The group arrives at the first village. It seems peaceful, but Jade\'s clairvoyance is unreliable: an unknown force is blocking her sight. Xima\'s influence may have reached further than expected.',
  events:['Party settles in Vigil Village','Jade investigates the magical interference','Villagers share rumours of unusual events','The party searches for clues about Xima\'s followers'],
  unlocks:['Village exploration','NPC conversations','Side quests','Local reputation','Investigation quests'],
  rewards:['Faepool village access','New investigation quests','Regional quest board unlocked']},
 7:{ title:'The Festival of Vigil', loc:'🏮 Vigil Village Festival',
  chars:['jade','chad','sky'],
  sum:'While investigating, the party stays for the village\'s traditional festival. Wandering the festival, Jade begins to question her own feelings and the complicated relationships forming around her.',
  events:['Festival begins','Jade learns about Vigil traditions','Sky\'s feelings toward Jade become clearer','Chad\'s behaviour creates tension'],
  unlocks:['Bond events','Character conversations','Relationship points'],
  rewards:['Bond EXP','Village reputation']},
 8:{ title:'The Hidden Message', loc:'🏘 Vigil Village · 🌲 Faepool Forest',
  chars:['jade','chad','sky'],
  sum:'Jade receives an unexpected message connected to the wider mission. It forces the party to reconsider their assumptions. Jade begins to suspect the curse, her visions and the people around her may all be connected.',
  events:['New information received','Investigation deepens','Party follows new clues','Jade questions her own destiny'],
  unlocks:['Main quest branch','Quest choices','Story decisions'],
  rewards:['New story route unlocked','Codex entries added']},
 9:{ title:'The Dark Influence', loc:'🌲 Faepool Forest',
  chars:['jade','chad','sky'],
  sum:'The party finds evidence that Xima\'s influence is affecting the region. Faepool\'s peaceful appearance hides deeper problems, and corrupted enemies appear. Jade must rely on both her combat skills and her unstable powers.',
  events:['First major encounters with corrupted enemies','Investigation into Xima\'s followers','Jade\'s powers become harder to control'],
  unlocks:['Field combat expansion','Enemy encounters','Skill upgrades','Equipment upgrades'],
  rewards:['Combat EXP','New skills','Enemy codex (bestiary) entries']},
 10:{ title:'The Swamp of Frog Mahan', loc:'🐸 Frog Mahan Swamp — poison marsh, hidden paths, corrupted forest',
  chars:['jade','chad','sky'],
  sum:'Following clues, the party travels toward the territory of Frog Mahan, one of Xima\'s weaker servants. The swamp tests their teamwork. Jade learns that defeating Xima\'s followers may reveal more about the curse.',
  events:['Party enters the swamp','Battles corrupted creatures','Discovers Frog Mahan\'s influence','Prepares for a major confrontation'],
  unlocks:['Boss battle system','Status effects','Environmental hazards','Boss patterns'],
  rewards:['Boss reward','Rare materials','New abilities']},
 11:{ title:'The Truth Beneath Faepool', loc:'🌲 Faepool Territory — ancient forest path, forgotten ruins, hidden caves',
  chars:['jade','chad','sky'],
  sum:'The party uncovers deeper secrets: the disturbances are part of a larger connection to Xima\'s curse. With her clairvoyance still unstable, Jade relies more on her companions and learns that not every truth can be found through visions.',
  events:['Party investigates ancient locations','Jade discovers traces of old magic','Chad and Sky assist Jade in different ways','More about Xima\'s influence is revealed'],
  unlocks:['Ancient ruin exploration','Puzzle areas','Hidden treasures','Lore discoveries'],
  rewards:['Ancient records added to Codex','New equipment','Party EXP']},
 12:{ title:'The Witch\'s Shadow', loc:'🌫 Ancient Ruins',
  chars:['jade','chad','sky'],
  sum:'The party finds evidence of the ancient witch whose curse has shaped Tribute\'s history. Jade\'s visions grow stronger but unclear: warnings, memories, or a connection to something deeper in herself.',
  events:['Jade encounters traces of ancient magic','Xima\'s presence becomes more apparent','The curse may have multiple layers','Jade questions her connection to the past'],
  unlocks:['Vision events','Story visions','Hidden lore scenes','Prophecy fragments'],
  rewards:['Codex entries: Xima, Ancient Magic, Tribute History']},
 13:{ title:'The Border of Faepool', loc:'⚓ Faepool Border — harbour, trading posts, border settlements',
  chars:['jade','chad','sky'],
  sum:'The party reaches the edge of Faepool and prepares for the next stage. Chad is no longer simply a mercenary and Sky\'s loyalty has become important, but unresolved feelings and hidden secrets create tension in the group.',
  events:['Party prepares for the next journey','New information reaches Jade','Relationships develop','New threats are hinted'],
  unlocks:['Travel system expansion: boat travel','Regional map movement','Merchant system'],
  rewards:['New travel routes','Equipment upgrades']},
 14:{ title:'The Dark Inn Incident', loc:'🏚 Dark Inn',
  chars:['jade','chad','sky'],
  sum:'The party meets a mysterious inn tied to a dangerous incident. Jade wakes in a confusing situation involving Chad and unknown forces, leaving her unsure who to trust.',
  events:['Strange events occur at the inn','Jade investigates what happened','Chad\'s actions create uncertainty','Hidden motives begin surfacing'],
  unlocks:['Investigation events','Dialogue choices','Relationship changes','Hidden information'],
  rewards:['Character bond changes','New story clues']},
 15:{ title:'Journey Across the Sea', loc:'🌊 Sea Route — boat, ocean routes, coastal areas',
  chars:['jade','chad','sky'],
  sum:'Leaving the inn, the party travels by sea. Jade reflects on her strange powers, the ancient witch\'s messages and her feelings toward her companions. The journey forces the group to rely on each other.',
  events:['Party travels by boat','Jade continues searching for answers','Character relationships develop','New destination approaches'],
  unlocks:['Sea travel','Exploration routes','Random encounters','Travel events'],
  rewards:['New region unlocked','Story progression']},
 16:{ title:'The First Village', loc:'🏘 Vigil Village — village centre, riverside, forest paths, traditional market',
  chars:['jade','chad','sky'],
  sum:'After three days at sea, Jade and her companions arrive in Faepool: traditional forest villages far from the Imperial Capital. Their first destination is Vigil Village, where they begin investigating the strange events tied to Xima\'s influence. Jade\'s clairvoyance is blocked by an unknown force, so she must investigate through observation and teamwork.',
  events:['Party arrives at Faepool','Investigation begins in Vigil Village','Jade discovers interference affecting her powers','Party searches for clues about Xima\'s followers'],
  unlocks:['New region exploration','Village quests','Local NPC interactions','Investigation objectives'],
  rewards:['Faepool map expansion','New Codex entries','Regional quests unlocked']},
 17:{ title:'The Festival of Flowers', loc:'🏮 Vigil Village Festival',
  chars:['jade','chad','sky'],
  sum:'The party stays in Vigil Village while investigating. At the village\'s traditional festival, Jade observes Faepool customs and realises each region of Tribute has its own way of life. Personal emotions within the party grow more complicated.',
  events:['Festival begins','Jade learns Faepool customs','Sky\'s feelings become more apparent','Chad\'s relationship with Jade develops'],
  unlocks:['Bond events','Character conversations','Relationship scenes','Optional dialogue choices'],
  rewards:['Bond EXP','Village reputation','Festival items']},
 18:{ title:'The Blocked Vision', loc:'🌸 Vigil Village Shrine · 🌲 Ancient Forest',
  chars:['jade','chad','sky'],
  sum:'Jade keeps trying to use her clairvoyance but gets no clear answers. She realises the problem is not a weakness in her ability but interference from another powerful force, and begins exploring ancient teachings to strengthen herself.',
  events:['Jade investigates the source of the mental barrier','Ancient knowledge is discovered','The connection between powers and destiny becomes clearer'],
  unlocks:['Ability growth system: meditation at the Vigil Shrine','Skill enhancement','Ability progression'],
  rewards:['Clairvoyance upgrade path','New passive abilities']},
 19:{ title:'The Mysterious Stranger', loc:'🌲 Faepool Forest',
  chars:['jade','chad','sky'],
  sum:'New information suggests Tribute\'s problems are tied to larger forces beyond the current mission. Not every threat can be beaten by strength alone, and Jade learns the importance of understanding allies, enemies and hidden motives.',
  events:['New clues discovered','Party encounters unusual events','Hidden connections begin appearing'],
  unlocks:['Advanced exploration','Hidden areas','Optional quests','Rare items'],
  rewards:['New equipment','Lore discoveries']},
 20:{ title:'The Path Forward', loc:'🌲 Faepool Territory',
  chars:['jade','chad','sky'],
  sum:'With the Vigil Village investigation complete, the party prepares to go deeper into Faepool. Many questions remain, but they have grown stronger. Jade accepts that her destiny cannot be understood through visions alone: she must discover it through her choices.',
  events:['Investigation in Vigil concludes','Party prepares for the next stage','New mission objectives are received','Journey continues deeper into Tribute'],
  unlocks:['Chapter completion system'],
  rewards:['Story EXP','Character Bond EXP','New exploration routes']},
 21:{ title:'The Next Path', loc:'🌲 Faepool Wilderness — deep forest, hidden trails, ancient paths',
  chars:['jade','chad','sky'],
  sum:'Leaving Vigil Village, the party goes deeper into Faepool. They have found traces of Xima\'s influence but many questions remain. Jade begins to see that the journey is also about the truth of her own existence.',
  events:['Party leaves Vigil Village','New threats appear in the wilderness','Jade\'s visions reveal incomplete information','Party searches for the next clue'],
  unlocks:['Advanced field exploration','Hidden routes','Rare materials','Stronger enemies'],
  rewards:['New equipment','Story EXP','Codex updates']},
 22:{ title:'The Forgotten Ruins', loc:'🏛 Ancient Ruins',
  chars:['jade','chad','sky'],
  sum:'The party finds ruins holding traces of Tribute\'s ancient past. They show the island\'s history is more complicated than the stories passed down, and Jade finds evidence linking ancient powers, Xima\'s curse and her own abilities.',
  events:['Exploration of forgotten ruins','Ancient records discovered','New information about past conflicts revealed'],
  unlocks:['Ruin exploration','Puzzle sections','Lore collection','Hidden treasures'],
  rewards:['Ancient artefacts','Codex entries']},
 23:{ title:'The Trial of Strength', loc:'⚔ Ancient Trial Grounds',
  chars:['jade','chad','sky'],
  sum:'A challenge tests the party\'s teamwork. Jade learns individual strength is not enough, while Chad and Sky grow into stronger roles. The party grows closer by overcoming the trial together.',
  events:['Party faces combat challenge','Character abilities develop','Team cooperation becomes important'],
  unlocks:['Party skill system: combination attacks (bond pair skills) and team abilities'],
  rewards:['Skill upgrades','Bond EXP']},
 24:{ title:'The Hidden Settlement', loc:'🏘 Hidden Village',
  chars:['jade','chad','sky'],
  sum:'The party discovers a hidden settlement in Faepool. Its residents know the region and offer new clues about the forces affecting Tribute. Jade learns some people have chosen to hide from the conflicts around Xima.',
  events:['Party meets new villagers','Local secrets are uncovered','New mission information is obtained'],
  unlocks:['Settlement system','Side quests','Trading','NPC relationships'],
  rewards:['New items','Regional reputation']},
 25:{ title:'The Shadow Behind the Curse', loc:'🌫 Corrupted Forest',
  chars:['jade','chad','sky'],
  sum:'Stronger evidence shows Xima\'s influence is spreading. Jade must face the possibility that the enemy is tied to ancient events far beyond their understanding, and her role in Tribute\'s future grows more important.',
  events:['Corrupted areas discovered','Stronger enemies appear','Jade\'s destiny becomes clearer'],
  unlocks:['Elite enemy system','Strong monsters','Rare rewards','Challenge encounters'],
  rewards:['High-level equipment','Skill materials']},
 26:{ title:'The Road to Change', loc:'🌲 Faepool Borderlands',
  chars:['jade','chad','sky'],
  sum:'The party reaches a turning point. Their journey has changed them, and new challenges will introduce new allies and reshape the party.',
  events:['Party prepares for next mission','New characters are hinted','Future alliances begin forming'],
  unlocks:['Recruitment event system'],
  rewards:['New story routes']},
 27:{ title:'The Stranger of Faepool', loc:'🏘 Faepool Settlement',
  chars:['jade','chad','sky'],
  sum:'The party meets a mysterious figure with a complicated past. This chapter prepares the arrival of a new companion and widens the world beyond Jade\'s original mission.',
  events:['New character introduced','Party learns more about hidden conflicts','Future recruitment path begins'],
  unlocks:['Character introduction event'],
  rewards:['New character data','Codex update']},
 28:{ title:'Sally\'s Recruitment', loc:'🌹 Faepool Region',
  chars:['jade','chad','sky','sally'],
  sum:'Sally officially joins Jade\'s journey. Unlike the party\'s other warriors she fights with agility, deception and strategy rather than direct strength. Her arrival changes the party dynamic and opens new team compositions.',
  events:['Sally joins the party','Her background is revealed','Party formation expands'],
  unlocks:['Sally recruitable (Shadow Dancer)','Rogue skills','Evasion mechanics','Utility abilities'],
  rewards:['Sally unlocked','New party formations']},
 29:{ title:'The Lost Companion', loc:'🌲 Wilderness Route',
  chars:['jade','chad','sky','sally'],
  sum:'The journey continues amid new challenges. Past events catch up with the party, and the possibility of an old ally returning grows stronger. They prepare for the arrival of someone they believed lost.',
  events:['New threats appear','Past connections resurface','Party prepares for a major reunion'],
  unlocks:['Reunion quest'],
  rewards:['Story progression','New equipment']},
 30:{ title:'Levi\'s Return', loc:'🏹 Reunion Area',
  chars:['jade','chad','sky','sally','levi'],
  sum:'Levi Stanson returns after being believed lost. His survival shows the past was not what it seemed, brings closure to old mysteries and gives Jade a powerful ally. He entrusts Jade with a special crossbow with magical ammunition.',
  events:['Levi returns','Levi joins the party','Magical crossbow introduced','Magical bolt system unlocked'],
  unlocks:['Levi recruitment (Arcane Archer)','Enchanted Crossbow','Magical bolts: Flame, Frost, Lightning, Binding, Spirit'],
  rewards:['Levi unlocked','Enchanted Crossbow given to Jade']},
};
